export const CharacterConstants={
    CHAR_REQUEST: "CHAR_REQUEST",
    CHAR_SUCCESS: "CHAR_SUCCESS",
    CHAR_FAILURE: "CHAR_FAILURE",

    CHAR_DETAILS_REQUEST:"CHAR_DETAILS_REQUEST",
    CHAR_DETAILS_SUCCESS:"CHAR_DETAILS_SUCCESS",
    CHAR_DETAILS_FAILURE:"CHAR_DETAILS_FAILURE",
}